package me.bullyalert.dal.pojo;
// Generated Oct 18, 2013 4:23:39 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Subscriber generated by hbm2java
 */
public class Subscriber  implements java.io.Serializable {


     private String id;
     private String phone;
     private String email;
     private String twitterMonitor;
     private Date lastAlertSent;

    public Subscriber() {
    }

	
    public Subscriber(String id, String twitterMonitor) {
        this.id = id;
        this.twitterMonitor = twitterMonitor;
    }
    public Subscriber(String id, String phone, String email, String twitterMonitor, Date lastAlertSent) {
       this.id = id;
       this.phone = phone;
       this.email = email;
       this.twitterMonitor = twitterMonitor;
       this.lastAlertSent = lastAlertSent;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTwitterMonitor() {
        return this.twitterMonitor;
    }
    
    public void setTwitterMonitor(String twitterMonitor) {
        this.twitterMonitor = twitterMonitor;
    }
    public Date getLastAlertSent() {
        return this.lastAlertSent;
    }
    
    public void setLastAlertSent(Date lastAlertSent) {
        this.lastAlertSent = lastAlertSent;
    }




}


